export const BIOMES = [
  {
    n: '01', id: 'safe-shallows', regime: 'daylight', from: 0, to: 80,
    depth: '000—080 M', index: 'YÜZEY',
    name: 'Sığ Resifler', original: 'SAFE SHALLOWS',
    line: 'Işığın her şeyi gösterdiği yer.',
    text: 'Kurtarma kapsülünden ilk kez ayrıl. Mercanların arasında yönünü bul ve okyanusun sesine alış.',
    accent: 'var(--glow)', glow: '#7fe7ff', wiki: 'safe-shallows',
  },
  {
    n: '02', id: 'kelp-forest', regime: 'twilight', from: 80, to: 200,
    depth: '080—200 M', index: 'ALACAKARANLIK',
    name: 'Yosun Ormanı', original: 'KELP FOREST',
    line: 'Görüş azalır. Merak artar.',
    text: 'Creepvine gövdeleri akıntıyla birlikte hareket eder. Her gölge, yeni bir yaşam izi olabilir.',
    accent: 'var(--kelp)', glow: '#59d7c0', wiki: 'kelp-forest',
  },
  {
    n: '03', id: 'mushroom-forest', regime: 'midnight', from: 200, to: 525,
    depth: '200—525 M', index: 'ORTA DERİNLİK',
    name: 'Mantar Ormanı', original: 'MUSHROOM FOREST',
    line: 'Ağaçlar burada mantar.',
    text: 'Dev gövdeler karanlıkta dimdik durur, tepelerindeki tabakalar sıradan bir gelgit ritmi izler. Işıksız bu dipte yönü, ancak bu gövdelerin eğimi verir.',
    accent: 'var(--kelp)', glow: '#57b8ff', wiki: null,
  },
  {
    n: '04', id: 'lost-river', regime: 'deep', from: 525, to: 1065,
    depth: '525—1065 M', index: 'DERİNLİK',
    name: 'Kayıp Nehir', original: 'LOST RIVER',
    line: 'Bazı yollar yalnızca aşağı iner.',
    text: 'Fosillerin ve tuzlu akıntıların içinden geç. Burada ışığın yerini bilinmeyen alır.',
    accent: 'var(--bathyal)', glow: '#3f7ad9', wiki: 'lost-river',
  },
  {
    n: '05', id: 'bulb-zone', regime: 'biolum', from: 1065, to: 1400,
    depth: '1065—1400 M', index: 'BİYOLÜMİNESAN',
    name: 'Ampul Zonu', original: 'BULB ZONE',
    line: 'Karanlık, kendi ışığını üretir.',
    text: 'Duvarlara yayılan ampuller suyun hareketini yavaşça takip eder. Işık bir uyarı ya da bir davet gibi parlar; hangisi olduğunu ancak yaklaştığında anlarsın.',
    accent: 'var(--glow)', glow: '#b06cff', wiki: null,
  },
  {
    n: '06', id: 'sulfur-pits', regime: 'biolum', from: 1400, to: 1600,
    depth: '1400—1600 M', index: 'LAV AĞIZLARI',
    name: 'Kükürt Deposu', original: 'SULFUR PITS',
    line: 'Isı, derinliğin son kanıtı.',
    text: 'Bacalardan yükselen sıcak akıntılar çevreyi sarı bir buhara boğar. Burada nefes payı kısadır; ölçümü düşürmeden geç.',
    accent: 'var(--bathyal)', glow: '#f0b45a', wiki: null,
  },
]
